openapi: 3.0.3
info:
  title: LionRockJS Auth
  description: LionRockJS Auth
  version: 0.0.1
servers:
  - url: 'https//'
tags:
  - name: register
  - name: login
  - name: account
paths:
  /register:
    post:
      tags:
        - register
      summary: Register a new user
      responses:
        200:
          description: TBC
  /login:
    get:
      tags:
        - login
      summary: User Login Form
      responses:
        200:
          description: TBC
    post:
      tags:
        - login
      summary: Process Login
      responses:
        200:
          description: TBC
  /login/fail:
    get:
      tags:
        - login
      summary: User Login Fail
      responses:
        200:
          description: TBC
  /logout:
    get:
      tags:
        - login
      summary: User Logout
      responses:
        200:
          description: TBC
  /account:
    get:
      tags:
        - account
      summary: User Account Details
      responses:
        200:
          description: TBC
  /account/person:
    get:
      tags:
        - account
      summary: User Personal Details
      responses:
        200:
          description: TBC
    post:
      tags:
          - account
      summary: Update User Personal Details
      responses:
        200:
          description: TBC