openapi: 3.0.3
info:
  title: LionRockJS Auth
  description: LionRockJS Auth
  version: 0.0.1
servers:
  - url: 'https//'
paths:
  /register:
    post:
      tags:
        - register
      responses:
        200:
          description: TBC
  /login:
    get:
      tags:
        - login
      responses:
        200:
          description: TBC
    post:
      tags:
        - login
      responses:
        200:
          description: TBC
  /login/fail:
    get:
      tags:
        - login
      responses:
        200:
          description: TBC
  /logout:
    get:
      tags:
        - login
      responses:
        200:
          description: TBC
  /account:
    get:
      tags:
        - account
      responses:
        200:
          description: TBC
  /account/person:
    get:
      tags:
        - account
      responses:
        200:
          description: TBC
    post:
      tags:
          - account
      responses:
        200:
          description: TBC