@startuml
skinparam Shadowing false

#000:<color:#FFF>change password</color>;
fork
  ->have password;
  :input old password, new password, retype password<
  if(new password != old password AND new password = retype password) then (no)
    :password typo message>
    end
  else(yes)
    if(verify old password hash) then (invalid)
      :invalid old password >
      end;
    else (valid)
    endif
  endif
fork again
  ->no password;
  :new password, retype password<

  if(new password = retype password) then (no)
    :password typo message>
    end
  else (yes)
  endif
end fork
:hash new password with username/
:change password success message>
stop

@enduml